### ISSUE TITLE
Honeycomb Yoke

### ISSUE THREAD

**Issue by Scooter69** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#109]
The Battery switch is no longer active or binded to the Honeycomb yoke since last update.  Can use the mouse to turn battery on but still will not come on unless you trun the Honeycomb Battery on.  However the battery switch will not move with the Honecomb....You have to do both Mouse and Honeycomb to get the switch on.  Scooter

**Comment by magraina** [comment]
@NewoPL seems to be the key binding is lost?

**Comment by Scooter69** [comment]
yes tried to reset it but not fixable my end.   Thank You love your work!

**Comment by magraina** [comment]
@Scooter69 No, it's not that easy.

**Comment by Scooter69** [comment]
Sir thank you, I was just trying to give you info that I Deleted the assignment and Reassigned it to let you know for your investigation.      Thank You So Much!!!!!

**Comment by NewoPL** [comment]
For my tests it works. There must be something special about your controller. Could you confirm that ALT-B key binding works for you ? Could you try to bind TOGGLE MASTER BATTERY event to any other button / any other controller and see if it works ? I do not have HoneyComb to quickly find what is going on, I need help to find out more.

**Comment by magraina** [comment]
I have a Honeycomb.
I can test that too.
And I can also monitor what events are going on.

**Comment by Scooter69** [comment]
Ok Back, Ran a few test.  1. Used default paint for the test.  Moved the Batt to the ALT switch.  Did not work.  Moved the Batt to the BUS 1.  Did not work.  2. I have the Honeycomb Throttle Quad.  I assigned the Batt there and Did Not work.  For Kicks I selected Toggle Batt and the Switch Moved but being Toggle it did not turn on but did move the switch.  I also Set to the other Batt selections.  Such Batt Master On, Batt Master off.  Did not work.  I used Set Batt 1 selection did not work.  It is currently set to Set Battery On.  It worked fine in the pervious update.   To make it work I have to use the Mouse to turn on and Flip the Batt switch.  I could Disable the Batt switch for now so I'd have to use the mouse.  I hope this helps.  Thanks for letting me help Scooter

**Comment by NewoPL** [comment]
I don't have your volant but i have suspicion what may be wrong. Please try this version to see if it helps with the issue: https://github.com/NewoPL/msfs2020-C208-Improvment-Mod 
Did you use keyboard Alt+B shorttcut to enable battery ? does it work ?

**Comment by NewoPL** [comment]
magraina i did the pull request at the same time for you to chekout the patch and test with  honeycomb

**Comment by magraina** [comment]
Okay👍🏼

**Comment by Scooter69** [comment]
Ok I have v2201.2 installed MSFS v1.21.18.0.   I use MSFS Downloader App.  I did a install from the link above.  I did remove the MOD and switch works fine.  After I did the link above I did some test.  The first time I had the Sim running the Alt. B worked liked it supposed to.  But the HC yoke did not function Batt Sw. at all.   I closed the MSFS and was about to message but needed to verify some info so restarted the MSFS and same issue Happened the Alt. B moves the switch but did not power up until I turned on the HCY  Batt Switch.  I went in and checked the Key Board assignments and Alt B is set to "TOGGLE MASTER BATTERY" and the Honey C is set to "SET MASTER BATTERY" .  I did some test by setting up the Key bind to SET MASTER BAT with Alt B and did not even work and I assigned HC beside it did not work.  Just for kicks I did both to TOGGLE MASTER BATT of course the switch went crazy due to repeated KEY presses with the switch.  And Finally I deleted the HC Batt switch bind and got a dead plane.  The plane did not even power up with Alt B or Mouse click......Very Strange.  So I set everything back to the way it was and works but have to work together with Alt B and HC Batt Switch.   Thank You Scooter and yes I tried ALT B before trying the link above and it DID flip the switch just no power.   Thank You Scooter

**Comment by Scooter69** [comment]
Update....I restarted the SIM to make sure above.  With Alt B I get the plane switch to move but I don't get the Ding until HC Batt switch.  I also notice the Avionics fan doesn't kick on.  Now if I turn it off and use the Mouse to turn on the Batt switch then the HC I get the AV fan.  I hope I'm helping thanks Scooter.
