### ISSUE TITLE
Is the working-title G1000 mod still needed?

### ISSUE THREAD

**Issue by Midcon113** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#11]
Can no longer find the link?

**Comment by magraina** [comment]
@Midcon113 
Yes, cause they don't have fix that yet. They do actually have the focus on other things.
But check out there is a new version with a new fix for the new g1000 mod
[https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/releases/tag/v0.1.6](https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/releases/tag/v0.1.6)

**Comment by Midcon113** [comment]
Got the new version, appears to be working well now. Thanks!
