### ISSUE TITLE
Stby Alternator LED does not work according to POH

### ISSUE THREAD

**Issue by NewoPL** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#110]
According to POH:
_The STBY ALT PWR switch is a two-position toggle-type switch, labeled STBY ALT PWR. There is also an amber LED light located above the switch that comes on when the BATTERY switch is in the OFF position with STBY ALT PWR switch in the ON position. This is an alert to the operator to help prevent accidental discharging of the battery that can occur if the STBY ALT PWR switch is left ON after shutdown._

**Comment by NewoPL** [comment]
I have a fix for that which i submit in my next pull request

**Comment by magraina** [comment]
Great, Thank you!
