### ISSUE TITLE
Cockpit light knob controls inverted

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#117]
User feedback from flightsim.to
> Very nice MOD ! Gave the Caravan a new life ! Thank you very much for this ! I wrote a PM for you regarding something I found. Since you changed the cockpit light knobs names (CB/Pedestal/OVH to Left Flood) and (Left Flood to Center Flood), the knob controls are inverted (Left knob controlling the Center light and Center Knob controlling the left light). As for the rest, it works perfectly. Plane feels smoother and better to fly ! Many thanks !

**Comment by magraina** [comment]
> Not the rotation but the Left side knob is actually controlling the Center light and the Center Knob is controlling the Left side light ! A small detail but it would be very nice if you could fix it !

**Comment by NewoPL** [comment]
that one is already fixed by one of my patches in the current pull request

**Comment by magraina** [comment]
Okay, good! 
I haven't had a look on that yet
