### ISSUE TITLE
Max Payload is negativ

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#120]
![image](https://user-images.githubusercontent.com/33145691/156262851-7893f9e7-9f54-45fd-a63e-2f7b4b33be34.png)

**Comment by magraina** [comment]
Any Idea how that could have happened? @NewoPL

**Comment by magraina** [comment]
This bug also exists in stock version

**Comment by magraina** [comment]
I turns to normal when sliding the slider to zero.
Seems to be a calculation issue (I think it has nothing to do with the aircraft itself)

**Comment by NewoPL** [comment]
I see the same with SU8. it must be sim problem.
