### ISSUE TITLE
Aircraft is yaws extremely to the left

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#121]
![image](https://user-images.githubusercontent.com/33145691/156263151-dee21428-a893-4a06-9a83-3d82fe6ba099.png)

**Comment by magraina** [comment]
Any Idea how that could have happened? @NewoPL

**Comment by magraina** [comment]
This does not happened in stock version.

Seems to be a linear momentum which is proportional to the throttle.

**Comment by NewoPL** [comment]
They changed the complete propeller simulation in SU8
i noticed that the effect is strong, though still controllable
I did not fly the original model though much. I am curious to see if the
effect is the same there
we can take a look at how to decrease it.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by magraina** [comment]
Found it! Two numbers have been swapped

**Comment by NewoPL** [comment]
great catch.
do you know what
prop_moment_transfer_on_roll = 1
is ?
i cannot find it in SDK doc or in any other aircraft flight model
thanks
newo

**Comment by magraina** [comment]
Nope, couldn't find it too, but I included it.
I haven't noticed any changes.
