### ISSUE TITLE
Governor test button does not have a tooltip

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#122]
![image](https://user-images.githubusercontent.com/33145691/156424272-00e2f3da-7c9a-4452-8013-e0f42ecce2b7.png)

**Comment by NewoPL** [comment]
There is no default localised title for overspeed test. I guess it will require aircraft specific localised string

**Comment by magraina** [comment]
I haven't tried such things. But maybe it works if English exists (like a default).
Probably the community could help with some other languages 🤷🏼‍♀️.

I also got checklist on my list which has the same problem.

**Comment by magraina** [comment]
Fixed
