### ISSUE TITLE
Torque gauge has a different scaling between Engine and system page

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#127]
![image](https://user-images.githubusercontent.com/33145691/156448430-751b4a58-3a1c-4c0a-8979-24570b4d27f1.png)
![image](https://user-images.githubusercontent.com/33145691/156448462-7695f234-496d-4461-98eb-32eba9284f2a.png)

**Comment by NewoPL** [comment]
it should be fixed by this commit https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/pull/128/commits/9960594465104035a18036ed9ffe3016541ec2c8
