### ISSUE TITLE
Merge some of the files in my C208 mod to yours.

### ISSUE THREAD

**Issue by Drosofila** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#13]
Hi, I'm sorry if this is the wrong place to post this (It's not really an issue and I don't know how to use Github very well). I'm the creator of [this C208 mod](https://github.com/Dros0phila/C208-MSFS2020-Fix). I'm not very good with coding so I haven't been working on the mod for a while now. I just found your mod and it is really promising. I've added some of my modifications to your mod:

- Replaced the instrument panel texture so it reads "FLUID" rather than "FLUD"
- Set the position of the condition lever to "IDLE CUTOFF" when starting in cold & dark state.
- Made the Yaw Damper functional.

I also have modified engines.cfg and flightmodel.cfg, but it seems like you're already working on your own modifications to these files. I'm attaching a version of the mod with my engine and flight model modifications and another one without it (only with the changes mentioned above).

My engines.cfg is tuned to make the fuel flow and power settings work as close as possible to reality within MSFS limitations, based on the POH and videos other pilots have provided. My flight model aims to increase the drag generated by the flaps based on the feedback I got from a real life Caravan pilot, among other things like elevator trim sensibility. 

[sheepind-cessna208b-g1000 (With engine and flight model by drosophila).zip](https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/files/5550295/sheepind-cessna208b-g1000.With.engine.and.flight.model.by.drosophila.zip)

[sheepind-cessna208b-g1000 (Drosophila).zip](https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/files/5550296/sheepind-cessna208b-g1000.Drosophila.zip)

If you don't like some of the changes I've made (or all of them) it's totally fine, it's just that I would like to work together with other devs so we can have a better Caravan in MSFS. Feel free to use and modify any of my work. :-)

**Comment by magraina** [comment]
@Dros0phila Thank you! It is just the right place!
I will have a look on it. I already thought about some changes, like them which you are already have done.
I will see how this could be merged.

**Comment by magraina** [comment]
Project is continued on https://flightsim.to/file/8060/cessna-208b-grand-caravan-ex-improvement-mod
