### ISSUE TITLE
Another key binding or event thing

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#130]
[FlightBurky ](https://flightsim.to/profile/FlightBurky)

> Starting a flight from a parking area the C208 Systems are energized (you can hear teh electrical giros). The battery master switch can be moved but has no influence (you cannot shut off). But when I switch the Battery with the Saitek Panel it works - but the ingame battery switch still shows no reaction.

**Comment by magraina** [comment]
Im trying to find out what he is using

**Comment by NewoPL** [comment]
maybe fixed by https://github.com/NewoPL/msfs2020-C208-Improvment-Mod/commit/4c9391998b19b889e56b6169dfc2319bf95a2d4c

**Comment by magraina** [comment]
I will check

**Comment by magraina** [comment]
Cannot reproduce with actual version.
All key bindings / events work.
