### ISSUE TITLE
Fluid Control Primary High switch is reversed?

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#132]
[SJK](https://flightsim.to/profile/SJK)

 
>Fluid Control Primary High switch is reversed? Thanx for the mod I love it.

[Magraina ](https://flightsim.to/profile/Magraina)
>What do you mean by reversed?

[SJK ](https://flightsim.to/profile/SJK)

>Up goes down and down goes up. When the mouse icon shows that I will be lifting the switch and I click it actually goes down.

[Magraina ](https://flightsim.to/profile/Magraina)

>Okay we will check that

**Comment by NewoPL** [comment]
I do not understand what it means. It looks OK to me.

**Comment by magraina** [comment]
Cannot reproduce this issue but found another
