### ISSUE TITLE
The Avionics standby power and Avionics 2 switches do not function per the real aircraft?

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#135]
[Sling380](https://forums.flightsimulator.com/u/Sling380)
>The Avionics standby power and Avionics 2 switches do not function per the real aircraft as i believe was the intention.
Avionics standby power when on should supply an alternative means of power to the Avionics 1 bus but it appears to do not a lot.
Avioncs 2 should turn on the Avionics 2 bus regardless of the state of Avionics 1 but it does not.
The Avionics 1 and Avionics cross-tie switches work as expected.

**Comment by magraina** [comment]
### AVIONICS STANDBY POWER SWITCH

The AVIONICS STBY PWR switch is a guarded two-position switch/ breaker,  labeled AVIONICS STBY  PWR. The guard covering this switch must be lifted in order to select the ON position. When switched ON, the standby electrical system directly  provides power to the AVN BUS 1. When switched OFF,  the standby electrical  system may provide extra power to the avionics buses via the main  power distribution bus, provided the STBY PWR circuit breakers on the electrical buses are not pulled. When operating solely  on standby power, both AVIONICS No. 1 and No. 2 power switches  should be OFF to avoid feeding a possible fault in the primary power system.

### AVIONICS BUS TIE SWITCH

The AVIONICS BUS TIE switch is a two-position guarded toggle-type switch located on the left  sidewall switch and circuit breaker panel. The switch connects the AVN BUS 1 and AVN BUS 2 together in the event of failure of either bus  feeder circuit. Because power for each avionics bus is supplied from  a separate current limiter on the power distribution bus, failure of a current limiter can cause failure of the affected bus. Placing the AVIONICS BUS TIE switch  to the ON position will  restore power to the failed bus. Operation without both bus feeder circuits  may require an avionics load reduction, depending on equipment installed.

**Comment by magraina** [comment]
So if Bus Tie Switch is set, then both Avionics will conected, which means 
If only one Avionics switch is active or if Standby Avionics switch is active then both Avionics are on.

![Screenshot_20220310-035619.png](https://user-images.githubusercontent.com/33145691/157579593-f2a995a8-28db-45c3-9cff-e7447e8b8fcc.png)

The standby avionics switch connects Avionics Bus 1 if Standby Alternator provides power.

![Screenshot_20220310-035654.png](https://user-images.githubusercontent.com/33145691/157579639-607b7300-8e62-40f5-bf20-6ff8404942a6.png)

**Comment by magraina** [comment]
In my testings the Switches work as expected.
The only thing I would expect different is, that the switches should work in reverse and the cover will shut them off.
But that is something I don't know.

**Comment by magraina** [comment]
So the connection isn't right.
The Alternator Bus is not directly connected to the Power distribution bus. It is connected to Bus 1 and 2
POH page 7-94 to 7-96

Also if Generator is active then something disables the connection between Power distribution bus and Alternator bus (even if this connection is not valid as described above).

@NewoPL

**Comment by NewoPL** [comment]
that is true,
I left it for simplification as electrically those two configurations are
equivalent right now, untill power breakers are simulated.
rewiring will not change anything about model or switches behaviour.

**Comment by NewoPL** [comment]
i don't remember it right now but creating a connection loop might have been a problem as well.
I will take a look why there is a diffrence between my fork and main branch though. If it works on my branch it should work in the main repo as well.

**Comment by magraina** [comment]
Okay it is always not easy. I don't know if there is a possibility to build in things like diodes, which the real thing have.
So this might be a limitation from the sim too.

**Comment by NewoPL** [comment]
i expect this patch to fix the behavior

**Comment by magraina** [comment]
Strange, I had some Issue, where it was not able to provide power from standby alternator to stby avionics (while generator is triped and battery is off).
The I restarted via CTRL+SHIFT+E and CTRL+E. This happens when starting on the runway.
So maybe there is some connection on bus missing

**Comment by magraina** [comment]
Oh no it is working. the engine just does not provide enough power to handle the consumption
If I use auto start, the engine is in high idle described at #139
