### ISSUE TITLE
Beta reverse is extremely powerful and speed up the plane very fast

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#141]
**Describe the bug**
Beta reverse is extremely powerful and speed up the plane very fast

**To Reproduce**
1. Start Engine CTRL+E
2. After start, release brake and put Throttle in full reverse
3. Now you should be scared!

**Comment by NewoPL** [comment]
reverse thrust has been limited by this commit:
https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/pull/147
