### ISSUE TITLE
The two fuel switches in the overhead panel doesn't work 

### ISSUE THREAD

**Issue by Smurfenstein** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#149]
The two fuel switches in the overhead panel doesn't work. I have to use ctrl-e to autostart the engine.

**Comment by NewoPL** [comment]
Have you tested without other mods?  Such issues often are caused by mods conflicts. without additional information it is impossible to understand the cause

**Comment by NewoPL** [comment]
cannot reproduce

**Comment by Smurfenstein** [comment]
Was caused by incompatible checklist mod.
