### ISSUE TITLE
GENERATORS OFF

### ISSUE THREAD

**Issue by JordiRab** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#154]
Yellow warning about GENERATORS OFF does not disappear

From cold&dark, follow the standard start up sequence and the warning messages dont disappear.

**Comment by evolchek** [comment]
FYI the workaround is to flip the switch to MOTOR position for a second.

**Comment by NewoPL** [comment]
THe fixed version is on the fork
https://github.com/NewoPL/msfs2020-C208-Improvment-Mod

**Comment by NewoPL** [comment]
Fixed in the latest release
