### ISSUE TITLE
Heading display is incorrect when using GPS NAV AP.

### ISSUE THREAD

**Issue by akimtda** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#158]
When I set the AP to GPS NAV, the PFD shows the aircraft's heading to the left of the GPS line. Most of the time I find it displays the heading and the icon of the aircraft being off by 4 degrees. The aircraft actually follows the GPS NAV line in the sim, so it seems to be simulating the correct heading, or always drifting to the right? I didn't see this happen with the stock aircraft, which lined up with the heading of the pink line.
<img width="700" alt="c208gpsnavap" src="https://user-images.githubusercontent.com/1487017/210399384-ad87ec04-cca7-4396-af27-ddd12de33c0d.png">

**Comment by magraina** [comment]
@akimtda 
That's normal.
It is because a airplane needs to fight against the wind to follow the line.
[http://www.aviation-history.com/theory/wind_drift.htm](http://www.aviation-history.com/theory/wind_drift.htm)
