### ISSUE TITLE
White Screens

### ISSUE THREAD

**Issue by yacskn** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#16]
Using Working Title's G1000 v.0.3.2 with the included fix running up-to-date MSFS. 
Screens look like this:
![White_Screens](https://user-images.githubusercontent.com/52584574/103370617-4d990080-4ade-11eb-8b3f-d3e2755050a1.png)

**Comment by magraina** [comment]
@yacskn This Mod is actual not ready for the actual Version

**Comment by magraina** [comment]
Project is continued on https://flightsim.to/file/8060/cessna-208b-grand-caravan-ex-improvement-mod
