### ISSUE TITLE
msfs2020-C208-Improvment-Mod

### ISSUE THREAD

**Issue by xintensorx** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#18]
I have all white G1000 screens. need help fixing this

**Comment by magraina** [comment]
> I have all white G1000 screens. need help fixing this

Please have a look on the mainpage. This mod is continued on another git.
This version is no longer compatible.

**Comment by magraina** [comment]
https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod
