### ISSUE TITLE
Beta Findings

### ISSUE THREAD

**Issue by TrentKama** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#25]
-CAS messages working*.
*Incompatibility with https://github.com/Working-Title-MSFS-Mods/fspackages/releases/tag/gx-v0.1.0-dev8 (CAS messages not showing up with this mod in the community folder).
-Reversion mode working.
-Engine pages working.
-Light mod working.
-Texture fixes working.

Physics changes: Aircraft not performing well, poor climb performance, high drag.
Since Sim Update 4 overhauled turbine performance and changed the C208B's configs drastically, we might be better off running with the vanilla flight_model.cfg with just the nose gear contact point tweaked for now.

point.0 = 1, -2.3, 0, -4.18, 750, 0, 0.5, **51.5**, 0.21, 3, 0.5, 0, 0, 0, 0, 0

**Comment by magraina** [comment]
Okay this is workingTitle shared data. So there is a need to fix all of them.
I had already suspected that the physics has changed.
Thank you for the feedback!
