### ISSUE TITLE
Prop MOI too low in vanilla cfg

### ISSUE THREAD

**Issue by AlisterBrenton** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#28]
Propeller MOI in default C208 engines.cfg is around 3 - suspect this is a typo as other turboprops of similar diameter have MOI between 15-30. Adjusting it to around 15 on the Caravan cures the 'paper prop' feel and RPM jumping

**Comment by magraina** [comment]
@AlisterBrenton yes, this will be part of the next release.

**Comment by magraina** [comment]
Changed moi for 2106.3
