### ISSUE TITLE
Breaks The TBM930 (and possibly other turboprops)

### ISSUE THREAD

**Issue by Elephant42** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#40]
With this mod installed the master alert system on the TBM930 (both vanilla and modded)  is broken.  The audible warning cannot be cancelled.

I have tracked it down to the file html_ui\Pages\VCockpit\Instruments\NavSystems\Shared\CommonPFD_MFD.js, if this file is left out the TBM works ok but obviously some functionality is lost in this mod.

I suspect that a better way to detect the presence of the C208 is required - (this.engineType == EngineType.ENGINE_TYPE_TURBOPROP) is obviously causing the following code to be active for all turboprops, not just the c208.

**Comment by magraina** [comment]
Okay that's interesting. We use a change like this for over a half year and no one ever got problems like that. 
I will check, what else I can do to ensure the TBM.

**Comment by magraina** [comment]
@Elephant42 The new version v2108.4 will fix this issue
