### ISSUE TITLE
Cabin lights

### ISSUE THREAD

**Issue by Marek2704** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#48]
On flight cabin lights are on all the time on the left-hand side, when cabin lights switch is ON then right-hand side lights are on, left-hand side is dark.

**Comment by magraina** [comment]
Yes that seem to be a new bug since SU5

**Comment by magraina** [comment]
They changed a lot in SU5!
The cabin light toggles not between On and Off, it toggles between right and left.
I have no Idea what is causing this issue. 
I spent now hours on trial and error (there is no documentation about this) but everything I tried will turn the light off but never turn it on again.
If someone has an idea, i would be thankful.

**Comment by magraina** [comment]
This is fix in the next release
