### ISSUE TITLE
Torque gauge without texture

### ISSUE THREAD

**Issue by mreisr** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#52]
I'm using the branch 6 hours ago

![torque gauge](https://user-images.githubusercontent.com/81477386/131949966-95446e00-5079-4089-8e22-990e0ac91a1f.png)

**Comment by magraina** [comment]
@mreisr Thanks for let me know!
This isn't tested and released yet, so there are maybe some bugs.

**Comment by mreisr** [comment]
> @mreisr Thanks for let me know!
> This isn't tested and released yet, so there are maybe some bugs.

No problem, I just downloaded it for testing. By the way, I apologize for being hasty, I didn't know you hadn't tested it yet.

**Comment by magraina** [comment]
Branch is everytime work in progress
Release are under release
https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/releases/latest
