### ISSUE TITLE
Stall speed is incorrect?

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#54]
A user shared this feedback:
I don't know how realistic this is or whether it happened in previous versions, but I updated to the latest and when landing I found the plane floats for an insane amount of time. I was going below red stall speed and the plane still wasn't going down. Then I tried to replicate it and I had no trouble flying at 50-40 knots, no stall warning. Stall speed says ~60.

**Comment by TrentKama** [comment]
I'll test this in flight to double check. Documented stall speeds are typically higher than real values as they're usually tested at;

- maximum gross weight
- center of gravity at forward limit
- 0 bank angle
- idle power, no flaps
- near standard atmospheric conditions

**Comment by magraina** [comment]
So they are not below where they should?

**Comment by TrentKama** [comment]
They should be fine. But I'll run some stall tests later to confirm.

**Comment by TrentKama** [comment]
C208B Stall Tests:
Conditions:
8807lbs
Maximum Forward Center of Gravity
Power Idle
Fuel Condition HIGH IDLE
Conditions: 15C at Sea Level
Altitude: <3000ft ASL

Buffet: Start of aerodynamic buffeting
LoC: Loss of Control

FLAPS UP(AFM 63KTS KIAS)
1- 70KTS KIAS(Buffet)
2- 66KTS KIAS(LoC)
3- 66KTS KIAS(LoC)
4- 74KTS KIAS(Buffet)
5- 70KTS KIAS(Buffet)

FLAPS T/O APR(AFM 57KTS KIAS)
1- 58KTS KIAS(LoC)
2- 56KTS KIAS(LoC)
3- 59KTS KIAS(Buffet)

FLAPS LAND(AFM 50KTS KIAS)
1- 47KTS KIAS(Buffet)
2- 45KTS KIAS(LoC)
3- 43KTS KIAS(LoC)
4- 47KTS KIAS(Buffet)

**Comment by magraina** [comment]
@TrentKama Sound great!
