### ISSUE TITLE
Condition Lever Does Not Respond to Keys or Controller Assignment

### ISSUE THREAD

**Issue by topcat1952** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#70]
Latest update (after SU6) the condition lever will not move forward or back using keyboard Ctrl+Shift+F2 or Ctrl+Shift+F3. My Warhog throttle assignments no longer respond either. These do work on the mixtures for other aircraft. I can move the condition lever with the mouse.

**Comment by magraina** [comment]
Yes that is a known bug by Asobo
I can't fix that

**Comment by topcat1952** [comment]
Understood. I just discover that now when I uninstalled your mod and tried it again only to find the problem still existed. 

 

Thanks. I guess I’ll wait until Asobo fixes it.

 

Denny Knepper

Newville, PA 17241

 ***@***.***> ***@***.***

**Comment by Cronch** [comment]
I tried it with the latest dev version and it is now working properly.
I think it was fixed by Asobo on SU7

**Comment by magraina** [comment]
Good to know. I haven't try it yet by my self

**Comment by magraina** [comment]
Is fixed by Asobo
