### ISSUE TITLE
Reverse Thrust to low

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#76]
I've noticed reverse now doesn't have much effect. Is this intentional? Turboprops I've flown have normally a fairly strong reverse, basically not needed as beta pulls you up pretty quick generally.

**Comment by NewoPL** [comment]
I have a fix for that on the branch which I will submit pull request for

**Comment by magraina** [comment]
Great!

**Comment by magraina** [comment]
Fixed
