### ISSUE TITLE
Fan sound on startup

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#82]
would add that I’d love to see (well, hear) the deck skin fans when you turn on the battery. In the real airplane, once you turn the battery on, things get fairly loud - see the video I recorded below as an example. Also note the chirp at 9 seconds is when power is applied to the avionics bus, that’d be cool to hear as well. I did some work with ambient sounds in P3D but haven’t looked at what MSFS offers so I admittedly have no idea if these can be added.

G1000 Caravan Battery on sounds:
https://youtu.be/mr7LX6DOI08

**Comment by magraina** [comment]
Let's see if there are possibilities

**Comment by NewoPL** [comment]
The hum after switching the battery on is there currently in the model. Additionally, on MSFS model the first sound that is played is the Autopilot disengage notification. There is no such sound on the real plane as I can see on the video. It should be easy to get rid off. As for the chirp I have the impression that it is heard after switching on the avionics

**Comment by magraina** [comment]
Yes that's also my impression

**Comment by NewoPL** [comment]
they fixed the autopilot disengage warning when switchin on battery. Adding addtional sounds would require rebuilding the whole sound package. it will not be a quick fix. the whole wise project needs to be recreated first.

**Comment by magraina** [comment]
Oh sounds like a lot of work. I don't know anything about how it works

**Comment by NewoPL** [comment]
The improvement is ready on the branch
https://github.com/NewoPL/msfs2020-C208-Improvment-Mod

**Comment by magraina** [comment]
> The improvement is ready on the branch
> https://github.com/NewoPL/msfs2020-C208-Improvment-Mod

@NewoPL I stopped working on the mod as I have not really time for it.
You can either release it by yourself or I can merge it and if it is well tested I can release it. But I'm currently not able to test it.

**Comment by NewoPL** [comment]
fixed in the last release
