### ISSUE TITLE
Insufficient power after recent ASOBO updates

### ISSUE THREAD

**Issue by 39crauds33** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#94]
In the past C208B was very efficient simulation bush flights in Papua New Guinea.  But now it does not have enough power to manage upslope runways during taxi nor enough power to reach takeoff speed on short downslopes and reverse thrust is almost non-existent.   Also, as already mentioned, power changes and switching to reverse takes too long to activate.

**Comment by magraina** [comment]
Reverse thrust will be better in the next release.
Power hasn't changed since much since SU4, as far as I noticed? And is very close to the POH.
At least it has something to do with a lot of conditions like weather, weight and length of the runway.
If these conditions are bad, you cannot flight.

**Comment by 39crauds33** [comment]
I try to replicate Ryan (missionary bush pilot) flights from Youtube.  He
uses a Kodiak now but used to use the Caravan.  I have been retracing
flights like these for months using the Caravan successfully, but the other
day I ran into problems with lag in acceleration and lack of sufficient
reverse thrust.  My assumption was that ASOBO had tinkered with something
in their recent January update that has affected performance.  But, as you
say, it might just have been a unique set of weather and load (or something
in the community folder) that caused my issue.  I will continue to test fly
to different bush strips with the Caravan.  BTW it seems that 208B has a
higher stall speed in all configurations than the Kodiak.  Combine that
with slow acceleration and success of flights in and out of these short
high mountain strips can be marginal at best.  Thanks for responding and
keep up the great work!

**Comment by 39crauds33** [comment]
Checking POH, Vso should be 50 KIAS and Vs1 should be 61 KIAS.  It seems mod has Vs0 as 60 KIAS.  That makes quite a difference on soft field takeoffs and Vref speeds on short field landings

**Comment by magraina** [comment]
@39crauds33 
Stall Speed variates on different conditions.
- Total weight
- center of gravity
- bank angle
- flaps
- atmospheric conditions

These numbers you are referring to are in KTAS not in KIAS:

![image](https://user-images.githubusercontent.com/33145691/149644020-4c8a6a21-7631-42d0-9226-20a542f7dad5.png)

Our testing's:
https://github.com/SheepCreativeSoftware/msfs2020-C208-Improvment-Mod/issues/54#issuecomment-956050936

**Comment by 39crauds33** [comment]
Got it, thanks!
