### ISSUE TITLE
The battery consumes current event when fully charged

### ISSUE THREAD

**Issue by NewoPL** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#96]
Simulator issue that can be worked around.

**Comment by magraina** [comment]
Fixed that (Visual)

**Comment by NewoPL** [comment]
Hi magraina, i can see we worked on the same issue at the same time :)
If you want to take a look at my proposal i can make a pull request
I modelled / faked the charging characteristic. - Avionics shows the maximum current of 50 A with fully discharged battery and the current drops gradully to almost zero when battery is fully charged.

**Comment by NewoPL** [comment]
I remember that i read in POH that the indicated current is positive when the battery is charging and negative when the battery is discharging. it is the other way around than the sim is indicating.

**Comment by magraina** [comment]
Yes that's what the POH says

**Comment by magraina** [comment]
No problem. I think that's good to combine
