### ISSUE TITLE
enable front lights with cabin light switch

### ISSUE THREAD

**Issue by magraina** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#97]
**NewoPL**: Cabin Lights: POH is saying the same switch should also enable front lights. That is left for improvement later.

**Comment by NewoPL** [comment]
Magraina you can reject this defect. After studing POH it looks like the front cockpit lights are not connected with cabin and curtesy lights. I made some general improvments to the interior lighting with pull request #116. Right now after switching on the cabin lights in the back there is little ambient light upront which also helps to find your way around the cockpit.

**Comment by magraina** [comment]
@NewoPL okay good to know.
I will have a look on it!
Thank you for your work!
